import chalk from 'chalk';
import { writeFileSync } from 'fs';
import { join } from 'path';
import fsExtra from 'fs-extra';
import { getProjectRoot, readContext, contextExists } from './config.js';

const { ensureDirSync } = fsExtra;

function buildDoc(ctx, preamble = '') {
  const { project, session } = ctx;
  const lines = [];

  if (preamble) lines.push(preamble, '');

  lines.push(`# ${project.name}`);
  if (project.description) lines.push('', project.description);
  if (project.stack?.length) lines.push('', `**Stack:** ${project.stack.join(', ')}`);

  if (project.conventions?.length) {
    lines.push('', '## Conventions');
    project.conventions.forEach(c => lines.push(`- ${c}`));
  }

  if (project.offLimits?.length) {
    lines.push('', '## Off-limits');
    project.offLimits.forEach(f => lines.push(`- ${f}`));
  }

  lines.push('', '---', '', '## Current Session');
  lines.push(`_Last updated: ${session.lastUpdated}_`, '');
  if (session.summary) lines.push(session.summary);

  if (session.decisions?.length) {
    lines.push('', '### Decisions made');
    session.decisions.forEach(d => lines.push(`- ${d}`));
  }
  if (session.inProgress?.length) {
    lines.push('', '### In progress');
    session.inProgress.forEach(i => lines.push(`- ${i}`));
  }
  if (session.blockers?.length) {
    lines.push('', '### Blockers');
    session.blockers.forEach(b => lines.push(`- ${b}`));
  }
  if (session.nextSteps?.length) {
    lines.push('', '### Next steps');
    session.nextSteps.forEach(n => lines.push(`- ${n}`));
  }
  if (session.notes) {
    lines.push('', '### Notes', session.notes);
  }

  lines.push('', '---', '', '_Auto-generated by [ai-context](https://www.npmjs.com/package/@naresh699/ai-context). Run `aic sync` to update._');

  return lines.join('\n');
}

export function syncClaude(root, ctx) {
  writeFileSync(join(root, 'CLAUDE.md'), buildDoc(ctx), 'utf8');
  ensureDirSync(join(root, '.claude'));
  writeFileSync(join(root, '.claude', 'session-context.json'), JSON.stringify(ctx.session, null, 2), 'utf8');
  return ['CLAUDE.md', '.claude/session-context.json'];
}

export function syncCursor(root, ctx) {
  writeFileSync(join(root, '.cursorrules'), buildDoc(ctx), 'utf8');
  return ['.cursorrules'];
}

export function syncCopilot(root, ctx) {
  ensureDirSync(join(root, '.github'));
  writeFileSync(
    join(root, '.github', 'copilot-instructions.md'),
    buildDoc(ctx, '<!-- Auto-generated by ai-context — do not edit directly -->'),
    'utf8'
  );
  return ['.github/copilot-instructions.md'];
}

export function syncAll(root, ctx) {
  const tools = ctx.tools || ['claude'];
  const synced = [];
  if (tools.includes('claude')) synced.push(...syncClaude(root, ctx));
  if (tools.includes('cursor')) synced.push(...syncCursor(root, ctx));
  if (tools.includes('copilot')) synced.push(...syncCopilot(root, ctx));
  return synced;
}

export async function syncCommand() {
  if (!contextExists()) {
    console.log(chalk.yellow('\n⚠  No context found. Run `aic init` first.\n'));
    return;
  }

  const ctx = readContext();
  const root = getProjectRoot();
  const synced = syncAll(root, ctx);

  console.log(chalk.bold('\n🔄 Sync complete\n'));
  synced.forEach(f => console.log(`  ${chalk.green('✓')} ${chalk.white(f)}`));
  console.log('');
}
